### ISSUE TITLE
Error in sge parsing

### ISSUE THREAD

**Issue by calchoo** [bcgsc/mavis#175]
From Alexander Fortuna

> Dear Mavis Team,
> 
> 
> I have been working to run MAVIS on our HPC which runs with SGE and have been running into the issue of parsing qstat content. I imagine our qstat content is formatted differently then it is at BCGSC. I have attached my qstat output as well as the error message. I am using mavis 2.2.0 and I am trying to validate star fusion transcriptome fusion transcripts.
> 
> 
> In the attached text file I included the tracebacks for two errors. The first I solved by altering the parse_qstat
> 
> 
> lines = [l for l in content.split('\n') if l.strip() and not l.startswith('=')]
> 
> 
> I have been working independently to alter the parse_qstat portion to solve error #2 but I am wondering if you had another suggestion. I would appreciate any insight.
> 
> 
> 
> Kind Regards,
>Alexander Fortuna
>

**Comment by calchoo** [comment]
@alexjfortuna, I've released a new version with the fix for qstat, could you test it out? There are still some improvements I would like to add for error handling on SGE but I will be working on including these in a future release

**Comment by alexjfortuna** [comment]
@calchoo I am no longer receiving SGE errors when MAVIS parses qstat. Thank you!
