### ISSUE TITLE
dash being inserted between letters in gene names while annotating with ncrna file

### ISSUE THREAD

**Issue by alexjfortuna** [bcgsc/mavis#195]
## Expected Behaviour
Samples annotating correctly and annotations in final summary file named correctly
mavis_Qz8stepNwGy4kJuh6cMnnb-v2-a1-chr10_chr10-C10orf68_CCDC7.legend.json

## Actual Behaviour
files are named like so:

filenames:
mavis_Qz8stepNwGy4kJuh6cMnnb-v2-a1-chr10_chr10-C-1-0-o-r-f-6-8_C-C-D-C-7.legend.json

gene1_aliases | gene2_aliases
7;C;C;C;D | 0;1;6;8;C;f;o;r
7;C;C;C;D | 0;1;6;8;C;f;o;r
4;I;N;S;T | M;N;T
1;9;C;D;K;T | 7;B;P;R;R

## Steps to Reproduce the Behaviour

Ran MAVIS as specified in documentation

Have you seen this behavior?

**Comment by creisle** [comment]
@alexjfortuna , that looks like something must be wrong with the aliases column in the annotations file. I'll check it out

**Comment by creisle** [comment]
@alexjfortuna sorry about that, I've replaced the annotations file at the original link with a new one I just generated. Could you try again with the new file? (download from the same link. should be 147M not instead of 146M). You won't need to update mavis itself, just the annotations file.

**Comment by alexjfortuna** [comment]
Hi @creisle we are testing now with new file, will report back! thank you for speedy assistance with this.

**Comment by alexjfortuna** [comment]
HI @creisle everything annotating correctly. Thank you.
