### ISSUE TITLE
Schedule : Stopping submission. Dependencies not complete

### ISSUE THREAD

**Issue by Nitin123-4** [bcgsc/mavis#226]
[2020-10-11 07:46:02] validate
[2020-10-11 07:46:02] annotate
[2020-10-11 07:46:04] loading: ['hg38.cytoBand.txt']
[2020-10-11 07:46:04] loading: ['ensembl_human_hg38.87.json']
[2020-10-11 07:50:41] loading: ['hg38.fa']
                        submitted MA_normal_batch-L8XXsViecS3kgponLaGqAr-1
                        MA_normal_batch-L8XXsViecS3kgponLaGqAr-1 (kVKgfnLz4EDNWJp7TrGfkS) is SUBMITTED
[2020-10-11 08:44:37] pairing
                        Stopping submission. Dependencies not complete
                        MP_batch-L8XXsViecS3kgponLaGqAr is NOT SUBMITTED
[2020-10-11 08:44:37] summary
                        MS_batch-L8XXsViecS3kgponLaGqAr is NOT SUBMITTED
                      rewriting: S103744.mavis.output/build.cfg

please help me to resolve this.

**Comment by Nitin123-4** [comment]
I think issue is there in annotate step:

(46326789, 'position not found in mapping', dict_keys([Interval(46326809, 46326947), Interval(46326948, 46433189), Interval(46433190, 46433505), Interval(46433506, 46435288), Interval(46435289, 46435396), Interval(46435397, 46447562), Interval(46447563, 46447692), Interval(46447693, 46450295), Interval(46450296, 46450349)]))
Traceback (most recent call last):
  File "/MG/SHARED/PIPELINES/RESEARCH/RH7/1.0/lib/python3.7/site-packages/mavis/main.py", line 373, in main
    annotate_main.main(**args, start_time=start_time)
  File "/MG/SHARED/PIPELINES/RESEARCH/RH7/1.0/lib/python3.7/site-packages/mavis/annotate/main.py", line 254, in main
    drawing, legend = draw(drawing_config, ann, reference_genome.content, template_metadata.content, drawings_directory)
  File "/MG/SHARED/PIPELINES/RESEARCH/RH7/1.0/lib/python3.7/site-packages/mavis/annotate/main.py", line 51, in draw
    **other_settings
  File "/MG/SHARED/PIPELINES/RESEARCH/RH7/1.0/lib/python3.7/site-packages/mavis/illustrate/diagram.py", line 222, in draw_sv_summary_diagram
    reference_genome=reference_genome
  File "/MG/SHARED/PIPELINES/RESEARCH/RH7/1.0/lib/python3.7/site-packages/mavis/illustrate/elements.py", line 429, in draw_ustranscript
    pixel = mapping.convert_ratioed_pos(b.start) | mapping.convert_ratioed_pos(b.end)
  File "/MG/SHARED/PIPELINES/RESEARCH/RH7/1.0/lib/python3.7/site-packages/mavis/interval.py", line 488, in convert_ratioed_pos
    raise IndexError(pos, 'position not found in mapping', self.mapping.keys())
IndexError: (46326789, 'position not found in mapping', dict_keys([Interval(46326809, 46326947), Interval(46326948, 46433189), Interval(46433190, 46433505), Interval(46433506, 46435288), Interval(46435289, 46435396), Interval(46435397, 46447562), Interval(46447563, 46447692), Interval(46447693, 46450295), Interval(46450296, 46450349)]))

**Comment by Nitin123-4** [comment]
46326789, 'position not found in mapping' This is giving issues for other samples also. 
For some samples where I don't have this position in vcf its working all fine.

Sample1: 

18      46326721        MantaDEL:249567:0:0:0:0:0       TGAGGGCTTCAGCGGCAGAGGGGAGACCGTCCAAGGAGGGCTTCAGCGGCAGAGGGGAGACCGTCCAAG   T       129     PASS    END=46326789;SVTYPE=DEL;SVLEN=-68;CIGAR=1M68D;CIPOS=0,95;HOMLEN=95;HOMSEQ=GAGGGCTTCAGCGGCAGAGGGGAGACCGTCCAAGGAGGGCTTCAGCGGCAGAGGGGAGACCGTCCAAGGAGGGCTTCAGCGGCAGAGGGGAGACC       GT:FT:GQ:PL:PR:SR       0/1:PASS:56:179,0,53:6,0:6,6

Sample2:

18      46326721        MantaDEL:314990:0:0:0:0:0       TGAGGGCTTCAGCGGCAGAGGGGAGACCGTCCAAGGAGGGCTTCAGCGGCAGAGGGGAGACCGTCCAAG   T       26      PASS    END=46326789;SVTYPE=DEL;SVLEN=-68;CIGAR=1M68D;CIPOS=0,95;HOMLEN=95;HOMSEQ=GAGGGCTTCAGCGGCAGAGGGGAGACCGTCCAAGGAGGGCTTCAGCGGCAGAGGGGAGACCGTCCAAGGAGGGCTTCAGCGGCAGAGGGGAGACC       GT:FT:GQ:PL:PR:SR       0/1:PASS:24:76,0,26:3,0:6,3

**Comment by Nitin123-4** [comment]
Please look into this.

**Comment by Nitin123-4** [comment]
Please update if have any solution.

**Comment by calchoo** [comment]
Hi @Nitin123-4 ,

Can I just confirm what version of mavis you're running?

I'm having difficulties replicating the bug, could you please post more information that is logged around the error and the arguments list?

e.g


```
[2020-10-14 15:57:56] arguments
                        annotation_filters = 'choose_more_annotated,choose_transcripts_by_priority'
                        annotations = ['/gsc/pipelines/mavis/reference_files/ensembl79_hg38_annotations.json']
                        breakpoint_color = '#000000'
                        command = 'annotate'
                        domain_color = '#ccccb3'
                        domain_mismatch_color = '#b2182b'
...

[2020-10-14 15:57:56] loading: ['/gsc/pipelines/mavis/reference_files/ensembl79_hg38_annotations.json']
[2020-10-14 16:06:03] loading: ['/gsc/pipelines/mavis/reference_files/hg38_reference_genome.fa']
                      (1 of 1) gathering annotations for BPP(Breakpoint(18:46326721-46326816L), Breakpoint(18:46326789R), opposing=False, seq='')
                      generated 1 annotations
                      opening for write: test/annotations.tab
                      opening for write: test/annotations.fusion-cdna.fa
                      (1 of 1) current annotation pLrnqtUcTiEYXQ9hmpVakL-a1 PreTranscript(ENSG00000141622:46326809-46450349, name=ENST00000593230) IntergenicRegion(18:46326789_46326789+) deletion
                      BPP(Breakpoint(18:46326789R), Breakpoint(18:46326809-46326816L), opposing=False, seq='')
```

**Comment by ramsainanduri** [comment]
MAVIS: 2.2.6
                      hostname: ##############
[2020-10-11 23:54:08] arguments
                        annotation_filters = 'choose_more_annotated,choose_transcripts_by_priority'
                        annotations = ['ensembl_human_hg38.87.json']
                        breakpoint_color = '#000000'
                        command = 'annotate'
                        domain_color = '#ccccb3'
                        domain_mismatch_color = '#b2182b'
                        domain_name_regex_filter = '^PF\\d+$'
                        domain_scaffold_color = '#000000'
                        draw_fusions_only = False
                        draw_non_synonymous_cdna_only = False
                        drawing_width_iter_increase = 500
                        exon_min_focus_size = 10
                        gene1_color = '#657e91'
                        gene1_color_selected = '#518dc5'
                        gene2_color = '#325556'
                        gene2_color_selected = '#4c9677'
                        inputs = ['Test_Sample.Manta/results/variants/Test_Sample.mavis.output/Test_Sample_normal_genome/cluster/batch-mHbxLxUFnjVHxPstPkTdNb-1.tab']
                        label_color = '#000000'
                        library = 'Test_Sample'
                        log = 'Test_Sample.Manta/results/variants/Test_Sample.mavis.output/Test_Sample_normal_genome/annotate/batch-mHbxLxUFnjVHxPstPkTdNb-1/job-MA_Test_Sample_batch-mHbxLxUFnjVHxPstPkTdNb-1-Nsekcx9gvoCdQwgUk56y8P.log'
                        log_level = 'INFO'
                        mask_fill = '#ffffff'
                        mask_opacity = 0.7
                        masking = ['hg38_masking.tab']
                        max_drawing_retries = 5
                        max_orf_cap = 3
                        max_proximity = 5000
                        min_domain_mapping_match = 0.9
                        min_orf_size = 300
                        novel_exon_color = '#5D3F6A'
                        output = 'Test_Sample.Manta/results/variants/Test_Sample.mavis.output/Test_Sample_normal_genome/annotate/batch-mHbxLxUFnjVHxPstPkTdNb-1'
                        protocol = 'genome'
                        reference_genome = ['hg38.fa']
                        scaffold_color = '#000000'
                        splice_color = '#000000'
                        template_metadata = ['hg38.cytoBand.txt']
                        width = 1000
                      cached content: ['hg38.cytoBand.txt']
                      creating output directory: 'Test_Sample.Manta/results/variants/Test_Sample.mavis.output/Test_Sample_normal_genome/annotate/batch-mHbxLxUFnjVHxPstPkTdNb-1/drawings'
                      loading: Test_Sample.Manta/results/variants/Test_Sample.mavis.output/Test_Sample_normal_genome/cluster/batch-mHbxLxUFnjVHxPstPkTdNb-1.tab
                      loaded 4715 breakpoint pairs
                      read 4715 breakpoint pairs
                      cached content: ['ensembl_human_hg38.87.json']
                      cached content: ['hg38.fa']
					  
                      (2534 of 5666) current annotation bVjnTJsjq6udLpS4yZYoLG-a1 PreTranscript(ENSG00000141622:46326809-46450349, name=ENST00000593230) IntergenicRegion(18:46326789_46326789+) deletion
                      BPP(Breakpoint(18:46326789R), Breakpoint(18:46326809-46326816L), opposing=False, seq='')
                      drawing attempt: 1 1000px
                      closing: Test_Sample.Manta/results/variants/Test_Sample.mavis.output/Test_Sample_normal_genome/annotate/batch-mHbxLxUFnjVHxPstPkTdNb-1/annotations.tab
                      closing: Test_Sample.Manta/results/variants/Test_Sample.mavis.output/Test_Sample_normal_genome/annotate/batch-mHbxLxUFnjVHxPstPkTdNb-1/annotations.fusion-cdna.fa
					  
(46326789, 'position not found in mapping', dict_keys([Interval(46326809, 46326947), Interval(46326948, 46433189), Interval(46433190, 46433505), Interval(46433506, 46435288), Interval(46435289, 46435396), Interval(46435397, 46447562), Interval(46447563, 46447692), Interval(46447693, 46450295), Interval(46450296, 46450349)]))
Traceback (most recent call last):
  File "/home/USER/.local/lib/python3.7/site-packages/mavis/main.py", line 373, in main
    annotate_main.main(**args, start_time=start_time)
  File "/home/USER/.local/lib/python3.7/site-packages/mavis/annotate/main.py", line 254, in main
    drawing, legend = draw(drawing_config, ann, reference_genome.content, template_metadata.content, drawings_directory)
  File "/home/USER/.local/lib/python3.7/site-packages/mavis/annotate/main.py", line 51, in draw
    **other_settings
  File "/home/USER/.local/lib/python3.7/site-packages/mavis/illustrate/diagram.py", line 222, in draw_sv_summary_diagram
    reference_genome=reference_genome
  File "/home/USER/.local/lib/python3.7/site-packages/mavis/illustrate/elements.py", line 429, in draw_ustranscript
    pixel = mapping.convert_ratioed_pos(b.start) | mapping.convert_ratioed_pos(b.end)
  File "/home/USER/.local/lib/python3.7/site-packages/mavis/interval.py", line 488, in convert_ratioed_pos
    raise IndexError(pos, 'position not found in mapping', self.mapping.keys())
IndexError: (46326789, 'position not found in mapping', dict_keys([Interval(46326809, 46326947), Interval(46326948, 46433189), Interval(46433190, 46433505), Interval(46433506, 46435288), Interval(46435289, 46435396), Interval(46435397, 46447562), Interval(46447563, 46447692), Interval(46447693, 46450295), Interval(46450296, 46450349)]))

**Comment by calchoo** [comment]
Thanks for the logs!

I have a fix for this that should be pushed for release by next week.

In the meantime, to get around this issue you can try run the jobs with these options set to true:
```
draw_fusions_only = True
draw_non_synonymous_cdna_only = True
```

**Comment by creisle** [comment]
v2.2.8 has now been released which includes this fix
