### ISSUE TITLE
Annotate sv caller outputs standalone

### ISSUE THREAD

**Issue by MorganHow** [bcgsc/mavis#240]
I would like to be able to annotate the output of some of the SV callers without running the entire pipeline like taking the output vcf from pindel and just annotate it.

Is this currently possible as I couldn't find documentation supporting it.

Thanks!

**Comment by creisle** [comment]
Yup! that's possible. The validate and clustering steps are optional and can be omitted. You will still need to run the setup/convert/annotate steps however

![pipeline options](https://mavis.readthedocs.io/en/latest/configuration/pipeline/)

You would be the 3rd configuration in the above settings. You can do this by using the `--skip_stage cluster validate` argument during the setup command

If you do not want the pairing or summary stages you can also run convert and then annotate individually. You can see options and help menus for any of the sub-stages via command line

```bash
mavis <subcommand> --help
```

**Comment by MorganHow** [comment]
Awesome I’ll have to give it a go! Thanks for the quick response
