### ISSUE TITLE
Error during MAVIS setup

### ISSUE THREAD

**Issue by sarahdada** [bcgsc/mavis#246]
**Describe the bug**
This bug shows the following error during setup, it might be an issue with parsing. I am running manta-1.4.0 , the data might be in the wrong format.

**To Reproduce**
Steps to reproduce the behavior: .cfg file was made using the commands
mavis config \
--library PG00038 genome normal False hg38_PG1.bam \
--library PG00037 genome normal False hg38_PG2.bam \
--library PG00048 genome diseased False hg38_PG3.bam \
--convert delly PG_dellysomatic_hg38.vcf delly \
--convert manta diploidSV.de_novo.vcf manta \
--assign PG1 delly manta \
--assign PG2 delly manta \
--assign PG3 delly manta \
 -w PG0001_2_3.cfg

**The problem**
1. run command 'mavis setup PG0001_2_3.cfg -o path/to/results'
2. See error ...
  File "/home/user/miniconda3/bin/mavis", line 8, in <module>
    sys.exit(main())
  File "/home/user/miniconda3/lib/python3.8/site-packages/mavis/main.py", line 600, in main
    raise err
  File "/home/user/miniconda3/lib/python3.8/site-packages/mavis/main.py", line 582, in main
    pipeline = _pipeline.Pipeline.build(config)
  File "/home/user/miniconda3/lib/python3.8/site-packages/mavis/schedule/pipeline.py", line 350, in build
    libconf.inputs = run_conversion(config, libconf, conversion_dir)
  File "/home/user/miniconda3/lib/python3.8/site-packages/mavis/schedule/pipeline.py", line 81, in run_conversion
    convert_tool_output(
  File "/home/user/miniconda3/lib/python3.8/site-packages/mavis/tools/__init__.py", line 34, in convert_tool_output
    _convert_tool_output(
  File "/home/user/miniconda3/lib/python3.8/site-packages/mavis/tools/__init__.py", line 276, in _convert_tool_output
    rows = read_vcf(input_file, file_type, log)
  File "/home/user/miniconda3/lib/python3.8/site-packages/mavis/tools/vcf.py", line 197, in convert_file
    raise err
  File "/home/user/miniconda3/lib/python3.8/site-packages/mavis/tools/vcf.py", line 194, in convert_file
    rows.extend(convert_record(vcf_record, log=log))
  File "/home/user/miniconda3/lib/python3.8/site-packages/mavis/tools/vcf.py", line 110, in convert_record
    chr2, end, orient1, orient2, ref, alt = parse_bnd_alt(alt)
  File "/home/user/miniconda3/lib/python3.8/site-packages/mavis/tools/vcf.py", line 74, in parse_bnd_alt
    raise NotImplementedError('alt specification in unexpected format', alt)
NotImplementedError: ('alt specification in unexpected format', ']chr19:27302623]')

**Expected behavior**
Consolidation of SV data

**Versions (please complete the following information):**
 - OS:  centos-07
 - Python Version 3.8.3
 - MAVIS 2.2.9
 - Blat

**Additional context**

**Comment by creisle** [comment]
@sarahdada could you include the vcf header and variant line in question? Which file did the error occur on (should have a log message for which one it was converting above the error)

To get the relevant lines you can use grep

```bash
grep 'chr19:27302623' diploidSV.de_novo.vc
```

and the header

```bash
grep '^##' diploidSV.de_novo.vc
```

Make sure to remove any identifiers before posting (library names, patient names, etc)

**Comment by sarahdada** [comment]
For grep chr19, it doesn't seem to come up with anything- so maybe the SV caller format is off 

Header:
##fileformat=VCFv4.1
##fileDate=20210415
##source=GenerateSVCandidates 1.4.0
##reference=file:///projects/file/hg38_no_alt.fa
##contig=<ID=chr1,length=248956422>
##contig=<ID=chr2,length=242193529>
##contig=<ID=chr3,length=198295559>
##contig=<ID=chr4,length=190214555>
##contig=<ID=chr5,length=181538259>
##contig=<ID=chr6,length=170805979>
##contig=<ID=chr7,length=159345973>
##contig=<ID=chr8,length=145138636>
##contig=<ID=chr9,length=138394717>
##contig=<ID=chr10,length=133797422>
##contig=<ID=chr11,length=135086622>
##contig=<ID=chr12,length=133275309>
##contig=<ID=chr13,length=114364328>
##contig=<ID=chr14,length=107043718>
##contig=<ID=chr15,length=101991189>
##contig=<ID=chr16,length=90338345>
##contig=<ID=chr17,length=83257441>
##contig=<ID=chr18,length=80373285>
##contig=<ID=chr19,length=58617616>
##contig=<ID=chr20,length=64444167>
##contig=<ID=chr21,length=46709983>
##contig=<ID=chr22,length=50818468>
##contig=<ID=chrX,length=156040895>
##contig=<ID=chrY,length=57227415>
##contig=<ID=chrM,length=16569>
##contig=<ID=chr1_KI270706v1_random,length=175055>
##contig=<ID=chr1_KI270707v1_random,length=32032>
##contig=<ID=chr1_KI270708v1_random,length=127682>
##contig=<ID=chr1_KI270709v1_random,length=66860>
##contig=<ID=chr1_KI270710v1_random,length=40176>
##contig=<ID=chr1_KI270711v1_random,length=42210>
##contig=<ID=chr1_KI270712v1_random,length=176043>
##contig=<ID=chr1_KI270713v1_random,length=40745>
##contig=<ID=chr1_KI270714v1_random,length=41717>
##contig=<ID=chr2_KI270715v1_random,length=161471>
##contig=<ID=chr2_KI270716v1_random,length=153799>
##contig=<ID=chr3_GL000221v1_random,length=155397>
##contig=<ID=chr4_GL000008v2_random,length=209709>
##contig=<ID=chr5_GL000208v1_random,length=92689>
##contig=<ID=chr9_KI270717v1_random,length=40062>
##contig=<ID=chr9_KI270718v1_random,length=38054>
##contig=<ID=chr9_KI270719v1_random,length=176845>
##contig=<ID=chr9_KI270720v1_random,length=39050>
##contig=<ID=chr11_KI270721v1_random,length=100316>
##contig=<ID=chr14_GL000009v2_random,length=201709>
##contig=<ID=chr14_GL000225v1_random,length=211173>
##contig=<ID=chr14_KI270722v1_random,length=194050>
##contig=<ID=chr14_GL000194v1_random,length=191469>
##contig=<ID=chr14_KI270723v1_random,length=38115>
##contig=<ID=chr14_KI270724v1_random,length=39555>
##contig=<ID=chr14_KI270725v1_random,length=172810>
##contig=<ID=chr14_KI270726v1_random,length=43739>
##contig=<ID=chr15_KI270727v1_random,length=448248>
##contig=<ID=chr16_KI270728v1_random,length=1872759>
##contig=<ID=chr17_GL000205v2_random,length=185591>
##contig=<ID=chr17_KI270729v1_random,length=280839>
##contig=<ID=chr17_KI270730v1_random,length=112551>
##contig=<ID=chr22_KI270731v1_random,length=150754>
##contig=<ID=chr22_KI270732v1_random,length=41543>
##contig=<ID=chr22_KI270733v1_random,length=179772>
##contig=<ID=chr22_KI270734v1_random,length=165050>
##contig=<ID=chr22_KI270735v1_random,length=42811>
##contig=<ID=chr22_KI270736v1_random,length=181920>
##contig=<ID=chr22_KI270737v1_random,length=103838>
##contig=<ID=chr22_KI270738v1_random,length=99375>
##contig=<ID=chr22_KI270739v1_random,length=73985>
##contig=<ID=chrY_KI270740v1_random,length=37240>
##contig=<ID=chrUn_KI270302v1,length=2274>
##contig=<ID=chrUn_KI270304v1,length=2165>
##contig=<ID=chrUn_KI270303v1,length=1942>
##contig=<ID=chrUn_KI270305v1,length=1472>
##contig=<ID=chrUn_KI270322v1,length=21476>
##contig=<ID=chrUn_KI270320v1,length=4416>
##contig=<ID=chrUn_KI270310v1,length=1201>
##contig=<ID=chrUn_KI270316v1,length=1444>
##contig=<ID=chrUn_KI270315v1,length=2276>
##contig=<ID=chrUn_KI270312v1,length=998>
##contig=<ID=chrUn_KI270311v1,length=12399>
##contig=<ID=chrUn_KI270317v1,length=37690>
##contig=<ID=chrUn_KI270412v1,length=1179>
##contig=<ID=chrUn_KI270411v1,length=2646>
##contig=<ID=chrUn_KI270414v1,length=2489>
##contig=<ID=chrUn_KI270419v1,length=1029>
##contig=<ID=chrUn_KI270418v1,length=2145>
##contig=<ID=chrUn_KI270420v1,length=2321>
##contig=<ID=chrUn_KI270424v1,length=2140>
##contig=<ID=chrUn_KI270417v1,length=2043>
##contig=<ID=chrUn_KI270422v1,length=1445>
##contig=<ID=chrUn_KI270423v1,length=981>
##contig=<ID=chrUn_KI270425v1,length=1884>
##contig=<ID=chrUn_KI270429v1,length=1361>
##contig=<ID=chrUn_KI270442v1,length=392061>
##contig=<ID=chrUn_KI270466v1,length=1233>
##contig=<ID=chrUn_KI270465v1,length=1774>
##contig=<ID=chrUn_KI270467v1,length=3920>
##contig=<ID=chrUn_KI270435v1,length=92983>
##contig=<ID=chrUn_KI270438v1,length=112505>
##contig=<ID=chrUn_KI270468v1,length=4055>
##contig=<ID=chrUn_KI270510v1,length=2415>
##contig=<ID=chrUn_KI270509v1,length=2318>
##contig=<ID=chrUn_KI270518v1,length=2186>
##contig=<ID=chrUn_KI270508v1,length=1951>
##contig=<ID=chrUn_KI270516v1,length=1300>
##contig=<ID=chrUn_KI270512v1,length=22689>
##contig=<ID=chrUn_KI270519v1,length=138126>
##contig=<ID=chrUn_KI270522v1,length=5674>
##contig=<ID=chrUn_KI270511v1,length=8127>
##contig=<ID=chrUn_KI270515v1,length=6361>
##contig=<ID=chrUn_KI270507v1,length=5353>
##contig=<ID=chrUn_KI270517v1,length=3253>
##contig=<ID=chrUn_KI270529v1,length=1899>
##contig=<ID=chrUn_KI270528v1,length=2983>
##contig=<ID=chrUn_KI270530v1,length=2168>
##contig=<ID=chrUn_KI270539v1,length=993>
##contig=<ID=chrUn_KI270538v1,length=91309>
##contig=<ID=chrUn_KI270544v1,length=1202>
##contig=<ID=chrUn_KI270548v1,length=1599>
##contig=<ID=chrUn_KI270583v1,length=1400>
##contig=<ID=chrUn_KI270587v1,length=2969>
##contig=<ID=chrUn_KI270580v1,length=1553>
##contig=<ID=chrUn_KI270581v1,length=7046>
##contig=<ID=chrUn_KI270579v1,length=31033>
##contig=<ID=chrUn_KI270589v1,length=44474>
##contig=<ID=chrUn_KI270590v1,length=4685>
##contig=<ID=chrUn_KI270584v1,length=4513>
##contig=<ID=chrUn_KI270582v1,length=6504>
##contig=<ID=chrUn_KI270588v1,length=6158>
##contig=<ID=chrUn_KI270593v1,length=3041>
##contig=<ID=chrUn_KI270591v1,length=5796>
##contig=<ID=chrUn_KI270330v1,length=1652>
##contig=<ID=chrUn_KI270329v1,length=1040>
##contig=<ID=chrUn_KI270334v1,length=1368>
##contig=<ID=chrUn_KI270333v1,length=2699>
##contig=<ID=chrUn_KI270335v1,length=1048>
##contig=<ID=chrUn_KI270338v1,length=1428>
##contig=<ID=chrUn_KI270340v1,length=1428>
##contig=<ID=chrUn_KI270336v1,length=1026>
##contig=<ID=chrUn_KI270337v1,length=1121>
##contig=<ID=chrUn_KI270363v1,length=1803>
##contig=<ID=chrUn_KI270364v1,length=2855>
##contig=<ID=chrUn_KI270362v1,length=3530>
##contig=<ID=chrUn_KI270366v1,length=8320>
##contig=<ID=chrUn_KI270378v1,length=1048>
##contig=<ID=chrUn_KI270379v1,length=1045>
##contig=<ID=chrUn_KI270389v1,length=1298>
##contig=<ID=chrUn_KI270390v1,length=2387>
##contig=<ID=chrUn_KI270387v1,length=1537>
##contig=<ID=chrUn_KI270395v1,length=1143>
##contig=<ID=chrUn_KI270396v1,length=1880>
##contig=<ID=chrUn_KI270388v1,length=1216>
##contig=<ID=chrUn_KI270394v1,length=970>
##contig=<ID=chrUn_KI270386v1,length=1788>
##contig=<ID=chrUn_KI270391v1,length=1484>
##contig=<ID=chrUn_KI270383v1,length=1750>
##contig=<ID=chrUn_KI270393v1,length=1308>
##contig=<ID=chrUn_KI270384v1,length=1658>
##contig=<ID=chrUn_KI270392v1,length=971>
##contig=<ID=chrUn_KI270381v1,length=1930>
##contig=<ID=chrUn_KI270385v1,length=990>
##contig=<ID=chrUn_KI270382v1,length=4215>
##contig=<ID=chrUn_KI270376v1,length=1136>
##contig=<ID=chrUn_KI270374v1,length=2656>
##contig=<ID=chrUn_KI270372v1,length=1650>
##contig=<ID=chrUn_KI270373v1,length=1451>
##contig=<ID=chrUn_KI270375v1,length=2378>
##contig=<ID=chrUn_KI270371v1,length=2805>
##contig=<ID=chrUn_KI270448v1,length=7992>
##contig=<ID=chrUn_KI270521v1,length=7642>
##contig=<ID=chrUn_GL000195v1,length=182896>
##contig=<ID=chrUn_GL000219v1,length=179198>
##contig=<ID=chrUn_GL000220v1,length=161802>
##contig=<ID=chrUn_GL000224v1,length=179693>
##contig=<ID=chrUn_KI270741v1,length=157432>
##contig=<ID=chrUn_GL000226v1,length=15008>
##contig=<ID=chrUn_GL000213v1,length=164239>
##contig=<ID=chrUn_KI270743v1,length=210658>
##contig=<ID=chrUn_KI270744v1,length=168472>
##contig=<ID=chrUn_KI270745v1,length=41891>
##contig=<ID=chrUn_KI270746v1,length=66486>
##contig=<ID=chrUn_KI270747v1,length=198735>
##contig=<ID=chrUn_KI270748v1,length=93321>
##contig=<ID=chrUn_KI270749v1,length=158759>
##contig=<ID=chrUn_KI270750v1,length=148850>
##contig=<ID=chrUn_KI270751v1,length=150742>
##contig=<ID=chrUn_KI270752v1,length=27745>
##contig=<ID=chrUn_KI270753v1,length=62944>
##contig=<ID=chrUn_KI270754v1,length=40191>
##contig=<ID=chrUn_KI270755v1,length=36723>
##contig=<ID=chrUn_KI270756v1,length=79590>
##contig=<ID=chrUn_KI270757v1,length=71251>
##contig=<ID=chrUn_GL000214v1,length=137718>
##contig=<ID=chrUn_KI270742v1,length=186739>
##contig=<ID=chrUn_GL000216v2,length=176608>
##contig=<ID=chrUn_GL000218v1,length=161147>
##contig=<ID=chrEBV,length=171823>
##INFO=<ID=IMPRECISE,Number=0,Type=Flag,Description="Imprecise structural variation">
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
##INFO=<ID=SVLEN,Number=.,Type=Integer,Description="Difference in length between REF and ALT alleles">
##INFO=<ID=END,Number=1,Type=Integer,Description="End position of the variant described in this record">
##INFO=<ID=CIPOS,Number=2,Type=Integer,Description="Confidence interval around POS">
##INFO=<ID=CIEND,Number=2,Type=Integer,Description="Confidence interval around END">
##INFO=<ID=CIGAR,Number=A,Type=String,Description="CIGAR alignment for each alternate indel allele">
##INFO=<ID=MATEID,Number=.,Type=String,Description="ID of mate breakend">
##INFO=<ID=EVENT,Number=1,Type=String,Description="ID of event associated to breakend">
##INFO=<ID=HOMLEN,Number=.,Type=Integer,Description="Length of base pair identical homology at event breakpoints">
##INFO=<ID=HOMSEQ,Number=.,Type=String,Description="Sequence of base pair identical homology at event breakpoints">
##INFO=<ID=SVINSLEN,Number=.,Type=Integer,Description="Length of insertion">
##INFO=<ID=SVINSSEQ,Number=.,Type=String,Description="Sequence of insertion">
##INFO=<ID=LEFT_SVINSSEQ,Number=.,Type=String,Description="Known left side of insertion for an insertion of unknown length">
##INFO=<ID=RIGHT_SVINSSEQ,Number=.,Type=String,Description="Known right side of insertion for an insertion of unknown length">
##INFO=<ID=INV3,Number=0,Type=Flag,Description="Inversion breakends open 3' of reported location">
##INFO=<ID=INV5,Number=0,Type=Flag,Description="Inversion breakends open 5' of reported location">
##INFO=<ID=BND_DEPTH,Number=1,Type=Integer,Description="Read depth at local translocation breakend">
##INFO=<ID=MATE_BND_DEPTH,Number=1,Type=Integer,Description="Read depth at remote translocation mate breakend">
##INFO=<ID=JUNCTION_QUAL,Number=1,Type=Integer,Description="If the SV junction is part of an EVENT (ie. a multi-adjacency variant), this field provides the QUAL value for the adjacency in question only">
##FORMAT=<ID=DQ,Number=1,Type=Integer,Description="De novo quality score">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=FT,Number=1,Type=String,Description="Sample filter, 'PASS' indicates that all filters have passed for this sample">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="Normalized, Phred-scaled likelihoods for genotypes as defined in the VCF specification">
##FORMAT=<ID=PR,Number=.,Type=Integer,Description="Spanning paired-read support for the ref and alt alleles in the order listed">
##FORMAT=<ID=SR,Number=.,Type=Integer,Description="Split reads for the ref and alt alleles in the order listed, for reads where P(allele|read)>0.999">
##FILTER=<ID=Ploidy,Description="For DEL & DUP variants, the genotypes of overlapping variants (with similar size) are inconsistent with diploid expectation">
##FILTER=<ID=MaxDepth,Description="Depth is greater than 3x the median chromosome depth near one or both variant breakends">
##FILTER=<ID=MaxMQ0Frac,Description="For a small variant (<1000 bases), the fraction of reads in all samples with MAPQ0 around either breakend exceeds 0.4">
##FILTER=<ID=NoPairSupport,Description="For variants significantly larger than the paired read fragment size, no paired reads support the alternate allele in any sample.">
##FILTER=<ID=MinQUAL,Description="QUAL score is less than 20">
##FILTER=<ID=MinGQ,Description="GQ score is less than 15 (filter applied at sample level and record level if all samples are filtered)">
##ALT=<ID=INV,Description="Inversion">
##ALT=<ID=DEL,Description="Deletion">
##ALT=<ID=INS,Description="Insertion">
##ALT=<ID=DUP:TANDEM,Description="Tandem Duplication">
##cmdline=/gsc/software/linux-x86_64-centos6/manta-1.4.0/bin/configManta.py --bam /projects/bam /projects/path//file1.bam --bam /projects/path/file2.bam --bam /projects/bam /projects/path/file3.bam --referenceFasta /projects/path/hg38_no_alt.fa --runDir /projects/path/MantaResults_withHeader/

**Comment by sarahdada** [comment]
DELLY vcf grep chr19 does get a result. I can't scroll up on error but can just quickly rerun

```(base) [sdada@gphost14 DellyResults_withHeader]$ grep 'chr19:27302623' dellyfile.vcf
chrUn_KI270516v1        2       BND00073768     N       ]chr19:27302623]        67      LowQual PRECISE;SVTYPE=BND;SVMETHOD=EMBL.DELLYv0.8.7;END=3;CHR2=chr19;POS2=27302623;PE=0;MAPQ=0;CT=5to3;CIPOS=-1,1;CIEND=-1,1;SRMAPQ=14;INSLEN=0;HOMLEN=0;SR=4;SRQ=0.951613;CONSENSUS=CAATTTGGAGAGTTTTGAGGCCTATTGTGGAAAGATATATCCTAAAATAAAAAATACACGGAAGCATTCTGAGAAACTTCATTGTTTTGTGTGCATTCAACTCACAGAGTTGAACCTATCT;CE=1.9285GT:GL:GQ:FT:RCL:RC:RCR:RDCN:DR:DV:RR:RV  0/1:-129.223,0,-44.7728:10000:PASS:0:110747:110747:2:0:0:19:59  0/1:-107.543,0,-42.0154:10000:PASS:0:95614:95614:2:0:0:16:41
(base) [sdada@gphost14 DellyResults_withHeader]$ grep 'chr19:27302623' PG0004859-BLD_PG0003514compared_dellysomatic_hg38header.vcf
chrUn_KI270516v1        2       BND00069701     N       ]chr19:27302623]        67      LowQual PRECISE;SVTYPE=BND;SVMETHOD=EMBL.DELLYv0.8.7;END=3;CHR2=chr19;POS2=27302623;PE=0;MAPQ=0;CT=5to3;CIPOS=-1,1;CIEND=-1,1;SRMAPQ=14;INSLEN=0;HOMLEN=0;SR=4;SRQ=0.951613;CONSENSUS=CAATTTGGAGAGTTTTGAGGCCTATTGTGGAAAGATATATCCTAAAATAAAAAATACACGGAAGCATTCTGAGAAACTTCATTGTTTTGTGTGCATTCAACTCACAGAGTTGAACCTATCT;CE=1.9285GT:GL:GQ:FT:RCL:RC:RCR:RDCN:DR:DV:RR:RV  0/1:-129.223,0,-44.7728:10000:PASS:0:110747:110747:2:0:0:19:59  0/1:-94.3442,0,-45.4931:10000:PASS:0:88163:88163:2:0:0:17:39 ```

**Comment by creisle** [comment]
ok so I actually might know what's going on here. It looks like the DELLY is using an alt format that is close but doesn't match the vcf 4.2 specification (despite the header)

```
r = reference base/seq
u = untemplated sequence/alternate sequence
p = chromosome:position
```

They have  `]p]` but we expect that to include sequences `]p]ur` The alternate sequence can be empty but the reference sequence we don't consider optional. @calchoo can you double check the VCF 4.2 format for this make sure I'm interpreting it correctly

**Comment by creisle** [comment]
What version of delly are you using?

**Comment by sarahdada** [comment]
/gsc/software/linux-x86_64-centos7/delly-0.8.7/bin/delly  is what i am using thanks cara!!

**Comment by sarahdada** [comment]
```I used delly-0.8.1 , am clearly making an error here 
(base) [sdada@gphost14 MAVIS]$ mavis setup file_both.cfg -o /projects/path/MAVIS
                      MAVIS: 2.2.9
                      hostname: gphost14.bcgsc.ca
[2021-04-29 16:30:22] arguments
                        command = 'setup'
                        config = '/projects/pathMAVIS/file_both.cfg'
                        log = None
                        log_level = 'INFO'
                        output = '/projects/path/MAVIS'
                        skip_stage = []
Traceback (most recent call last):
  File "/home/sdada/miniconda3/lib/python3.8/site-packages/mavis/util.py", line 65, in filepath
    file_list = bash_expands(path)
  File "/home/sdada/miniconda3/lib/python3.8/site-packages/mavis/util.py", line 158, in bash_expands
    raise FileNotFoundError('The expression does not match any files', expression)
FileNotFoundError: [Errno The expression does not match any files] None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sdada/miniconda3/bin/mavis", line 8, in <module>
    sys.exit(main())
  File "/home/sdada/miniconda3/lib/python3.8/site-packages/mavis/main.py", line 482, in main
    config = _config.MavisConfig.read(args.config)
  File "/home/sdada/miniconda3/lib/python3.8/site-packages/mavis/config.py", line 379, in read
    return MavisConfig(**config_dict)
  File "/home/sdada/miniconda3/lib/python3.8/site-packages/mavis/config.py", line 264, in __init__
    raise err
  File "/home/sdada/miniconda3/lib/python3.8/site-packages/mavis/config.py", line 257, in __init__
    self[sec] = validate_section(kwargs.pop(sec, {}), defaults, True)
  File "/home/sdada/miniconda3/lib/python3.8/site-packages/mavis/config.py", line 466, in validate_section
    value = cast_type(value)
  File "/home/sdada/miniconda3/lib/python3.8/site-packages/mavis/util.py", line 67, in filepath
    raise TypeError('File does not exist', path)
TypeError: Error in validating the reference section in the config. File does not exist None

**Comment by creisle** [comment]
> TypeError: Error in validating the reference section in the config. File does not exist None ```

This sounds like you didn't add a reference file you need? or you set it to None. What does the reference section of your mavis config look like?

**Comment by sarahdada** [comment]
Hi Cara, 

(Un)Shockingly you are right; I didnt have the right masking etc for my ref. Changed Ref. THANKS

**Comment by sarahdada** [comment]
``` 
Still looking like chrm 8. Really sorry if I'm messing up something w/delly
(base) [sdada@gphost14 MAVIS]$ mavis setup file.cfg -o /projects/path/MAVIS
                      MAVIS: 2.2.9
                      hostname: gphost14.bcgsc.ca
[2021-04-30 11:09:34] arguments
                        command = 'setup'
                        config = '/projects/path/MAVIS/file.cfg'
                        log = None
                        log_level = 'INFO'
                        output = '/projects/sdada_prj/sdada_scratch/MSSNG/yingsfiles/hg38_PG0003514_3838_4859_fastq_SV/MAVIS'
                        skip_stage = []
                      creating output directory: '/projects/sdada_prj/sdada_scratch/MSSNG/yingsfiles/hg38_PG0003514_3838_4859_fastq_SV/MAVIS/converted_inputs'
                      setting up the directory structure for PG0003838 as /projects/sdada_prj/sdada_scratch/MSSNG/yingsfiles/hg38_PG0003514_3838_4859_fastq_SV/MAVIS/PG0003838_normal_genome
                      converting input command: ['convert_tool_output', '/projects/path/DELLY_0.8.1/patientcompared_dellysomatic_v81_hg38header.vcf', 'delly', False]
                      reading: /projects/path/DELLY_0.8.1/patientcompared_dellysomatic_v81_hg38header.vcf
Traceback (most recent call last):
  File "/home/sdada/miniconda3/bin/mavis", line 8, in <module>
    sys.exit(main())
  File "/home/sdada/miniconda3/lib/python3.8/site-packages/mavis/main.py", line 600, in main
    raise err
  File "/home/sdada/miniconda3/lib/python3.8/site-packages/mavis/main.py", line 582, in main
    pipeline = _pipeline.Pipeline.build(config)
  File "/home/sdada/miniconda3/lib/python3.8/site-packages/mavis/schedule/pipeline.py", line 350, in build
    libconf.inputs = run_conversion(config, libconf, conversion_dir)
  File "/home/sdada/miniconda3/lib/python3.8/site-packages/mavis/schedule/pipeline.py", line 81, in run_conversion
    convert_tool_output(
  File "/home/sdada/miniconda3/lib/python3.8/site-packages/mavis/tools/__init__.py", line 34, in convert_tool_output
    _convert_tool_output(
  File "/home/sdada/miniconda3/lib/python3.8/site-packages/mavis/tools/__init__.py", line 276, in _convert_tool_output
    rows = read_vcf(input_file, file_type, log)
  File "/home/sdada/miniconda3/lib/python3.8/site-packages/mavis/tools/vcf.py", line 197, in convert_file
    raise err
  File "/home/sdada/miniconda3/lib/python3.8/site-packages/mavis/tools/vcf.py", line 194, in convert_file
    rows.extend(convert_record(vcf_record, log=log))
  File "/home/sdada/miniconda3/lib/python3.8/site-packages/mavis/tools/vcf.py", line 110, in convert_record
    chr2, end, orient1, orient2, ref, alt = parse_bnd_alt(alt)
  File "/home/sdada/miniconda3/lib/python3.8/site-packages/mavis/tools/vcf.py", line 74, in parse_bnd_alt
    raise NotImplementedError('alt specification in unexpected format', alt)
NotImplementedError: ('alt specification in unexpected format', ']chr8:43240816]') ```
