### ISSUE TITLE
Swap to pyproject.toml and setup.cfg instead of setup.cfg

### ISSUE THREAD

**Issue by creisle** [bcgsc/mavis#261]
In order to keep up to date with [PEP-517](https://www.python.org/dev/peps/pep-0517/), update the setup.cfg and add a pyproject.toml to work with the new version of setuptools and prep for new versions of package installs with python

See example from other gsc repo: https://github.com/bcgsc/pori_ipr_python/pull/55

see the setuptools docs for how to structure the setup.cfg: https://setuptools.pypa.io/en/latest/build_meta.html

- [ ] move metadata and dependency lists from setup.py to setup.cfg
- [ ] remove m2r dependency as it will no longer be required (please double check it is not used outside the setup.py)
- [ ] add pyproject.toml
- [ ] add setup.py stub for editable installs (should only be the setup call)

**Comment by creisle** [comment]
For the functions that are in the setup.py

- https://github.com/bcgsc/mavis/blob/develop/setup.py#L9 this one can just be removed
- leave this one https://github.com/bcgsc/mavis/blob/develop/setup.py#L35 in the setup.py stub for now, there may be a way to specify non-python dependencies better later but currently it isn't clear there is.

**Comment by creisle** [comment]
To help debugging the pysam dependency issues, I collected the frozen list of dependencies from the last mavis production install on our end (v2.2.9). This should give us an idea of what might have changed if we compare it to what we get now

```
Package                       Version
----------------------------- --------
alabaster                     0.7.12
Babel                         2.7.0
biopython                     1.73
bleach                        3.1.0
braceexpand                   0.1.2
certifi                       2019.3.9
chardet                       3.0.4
colour                        0.1.5
decorator                     4.4.0
Distance                      0.1.3
docutils                      0.14
idna                          2.8
imagesize                     1.1.0
Jinja2                        2.10.1
m2r                           0.2.1
MarkupSafe                    1.1.1
mavis                         2.2.6
mistune                       0.8.4
networkx                      1.11
numpy                         1.16.4
packaging                     19.0
pip                           21.3.1
pkginfo                       1.5.0.1
Pygments                      2.4.2
pyparsing                     2.4.0
pysam                         0.15.2
pytz                          2019.1
PyVCF                         0.6.8
readme-renderer               24.0
requests                      2.22.0
requests-toolbelt             0.9.1
setuptools                    59.6.0
Shapely                       1.7a1
shortuuid                     0.5.0
six                           1.12.0
snowballstemmer               1.2.1
Sphinx                        2.1.0
sphinx-rtd-theme              0.4.3
sphinxcontrib-applehelp       1.0.1
sphinxcontrib-devhelp         1.0.1
sphinxcontrib-htmlhelp        1.0.2
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.2
sphinxcontrib-serializinghtml 1.1.3
svgwrite                      1.3b2
tqdm                          4.32.1
twine                         1.13.0
urllib3                       1.25.3
webencodings                  0.5.1
wheel                         0.37.0
zc.buildout                   3.0.0b5
```

**Comment by zhemingfan** [comment]
Closing issue, will be integrated into v3.
