### ISSUE TITLE
error:('error: expected one of', {'duplication'}, 'but found', 'deletion'

### ISSUE THREAD

**Issue by Nitin123-4** [bcgsc/mavis#350]
I am running mavis and getting the following error:
[2023-04-22 00:02:08] pairing
                        submitted MP_batch-iF48bHs9AZUjtaxYuuAiS2
MP_batch-iF48bHs9AZUjtaxYuuAiS2 (k9BGiGaU38uASMJ3AeJJor) is SUBMITTED
                      error:('error: expected one of', {'duplication'}, 'but found', 'deletion', "BPP(Breakpoint(18:43906752R), Breakpoint(18:43906772-43906779L), opposing=False, seq='')", {'tracking_id': 'manta-MantaDEL:196338:0:0:0:0:0', 'library': 'Acute-eosinophilic-leukemia', 'validation_id': 'asQkU4z5QgYCdVyx8wBsGi', 'annotation_id': 'asQkU4z5QgYCdVyx8wBsGi-a1', 'event_type': 'deletion', 'gene1': None, 'gene1_direction': None, 'gene2': 'ENSG00000141622', 'gene2_direction': '5', 'gene1_aliases': None, 'gene2_aliases': 'RNF165', 'gene_product_type': None, 'transcript1': '18:43906752_43906752+', 'transcript2': 'ENST00000593230', 'fusion_splicing_pattern': None, 'fusion_cdna_coding_start': None, 'fusion_cdna_coding_end': None, 'fusion_mapped_domains': None, 'fusion_sequence_fasta_id': None, 'fusion_sequence_fasta_file': 
[2023-04-22 00:02:18] summary
                        Stopping submission. Dependencies not complete
                        MS_batch-iF48bHs9AZUjtaxYuuAiS2 is NOT SUBMITTED

**Comment by Nitin123-4** [comment]
Hi team, Please have a look at this request.

**Comment by calchoo** [comment]
Hi @Nitin123-4, sorry for the delayed response. Would you be able to provide the manta output for that event?

**Comment by Nitin123-4** [comment]
Hi Calchoo,

Please find attached vcf file.

I think it was:
chr18   43906684        MantaDEL:196338:0:0:0
[diploidSV.PASS.vcf.zip](https://github.com/bcgsc/mavis/files/11559767/diploidSV.PASS.vcf.zip)
:0:0       TGAGGGCTTCAGCGGCAGAGGGGAGACCGTCCAAGGAGGGCTTCAGCGGCAGAGGGGAGACCGTCCAAG   T       261     PASS    END=43906752;SVTYPE=DEL;SVLEN=-68;CIGAR=1M68D;CIPOS=0,95;HOMLEN=95;HOMSEQ=GAGGGCTTCAGCGGCAGAGGGGAGACCGTCCAAGGAGGGCTTCAGCGGCAGAGGGGAGACCGTCCAAGGAGGGCTTCAGCGGCAGAGGGGAGACC       GT:FT:GQ:PL:PR:SR       1/1:PASS:18:313,21,0:0,0:0,8

**Comment by calchoo** [comment]
@Nitin123-4 Are you able to pull that event from the annotation output file? It looks like the positions may have been adjusted in the validate stage as I'm not getting the same breakpoints when running the convert directly on the manta vcf event you posted.

Also what version of mavis are you using?

**Comment by calchoo** [comment]
Okay as @zhemingfan pointed out it looks like v2.2.11 is converting the event to 
`chr18   43906684        43906779        L       ?       None    chr18   43906752        43906752        R`
while v3.1.1 is converting the event to 
`chr18   43906684        43906752        L       ?       None    chr18   43906752        43906752        R`

Notice the break1 end doesn't go over the break2 end and therefore we shouldn't see this error in the future.
This was addressed in this commit: https://github.com/bcgsc/mavis/commit/7051fc9b9cbcc8b44b680d0de7a29c78096e2513

@Nitin123-4 are you able to use the latest version (v3.1.1) instead of v2.2.11?

**Comment by Nitin123-4** [comment]
Thanks for your response. I can see mavis V3 uses snakemake.

Is it possible to fix it in v2.2.11 ? maybe with updated breakpoint.py and vcf.py (https://github.com/bcgsc/mavis/commit/7051fc9b9cbcc8b44b680d0de7a29c78096e2513)

**Comment by calchoo** [comment]
I could try but it might be faster for you to use the convert from v3 and use the converted file in v2

**Comment by calchoo** [comment]
@Nitin123-4 This should be fixed in v2.2.12
